logging:
  level:
    com.yaoyuefu.peanut: INFO
  config: classpath:logback/logback-test.xml

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      druid: # 2.2.3开始提供全局druid参数，以下是默认值和druid原生保持一致
        initial-size: 0
        max-active: 2
        min-idle: 0
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      mp-enabled: true #默认为false，不要随便开启，有微小的性能损失
      primary: strategy #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      datasource:
        strategy:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/xhh_strategy_new?useSSL=false&zeroDateTimeBehavior=convertToNull
          driver-class-name: com.mysql.jdbc.Driver
        yiyiyuan:
#          username: strategy
#          password: egm1OHnuJUpMt!LxXW
#          url: jdbc:mysql://182.92.80.211:3306/xhh_test?useSSL=false&zeroDateTimeBehavior=convertToNull
          username: yiyiyuan_test
          password: LXW&O!s@9TVR1j#hmA
          url: jdbc:mysql://47.93.121.86:3306/xhh_test?useSSL=false&zeroDateTimeBehavior=convertToNull
        xhhOpen:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/xhh_open?useSSL=false&zeroDateTimeBehavior=convertToNull
        xhhAntifraud:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/xhh_antifraud?useSSL=false&zeroDateTimeBehavior=convertToNull
        analysisRepertory:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/analysis_repertory_tidb?useSSL=false&zeroDateTimeBehavior=convertToNull
        xhhCloud:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/xhh_cloudnew?useSSL=false&zeroDateTimeBehavior=convertToNull
        youxin:
#          username: strategy
#          password: egm1OHnuJUpMt!LxXW
#          url: jdbc:mysql://182.92.80.211:3306/yx_test?useSSL=false&zeroDateTimeBehavior=convertToNull
          username: yiyiyuan_test
          password: LXW&O!s@9TVR1j#hmA
          url: jdbc:mysql://47.93.121.86:3306/yx_test?useSSL=false&zeroDateTimeBehavior=convertToNull
        hksugou:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/loan_shop_sugou?useSSL=false&zeroDateTimeBehavior=convertToNull
        kysyigou:
          username: strategy
          password: egm1OHnuJUpMt!LxXW
          url: jdbc:mysql://182.92.80.211:3306/loan_shop_yigou?useSSL=false&zeroDateTimeBehavior=convertToNull
