#测试环境业务配置
spring:
  datasource:
    name: test
    url: jdbc:mysql://182.92.80.211:3306/xhh_cloudnew?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: strategy
    password: egm1OHnuJUpMt!LxXW
    driver-class-name:  com.mysql.jdbc.Driver
    # 使用hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

